### ISSUE TITLE
Reach data parity with StreamCompanion

### ISSUE THREAD

**Issue by S1n1st3rn3ss** [486c/rosu-memory#20]
Currently rosu-memory lacks data compared to SC

Useful data points:

- [x] BPM and current BPM (partly added in #19)
- [x] username (added based on replays in #19)
- [x] current score (added in #19)
- [x] current letter grade (added in #28)
- [x] background image of the current beatmap
- [x] current skin name (added in #26)
- [x] map ranked status (added in #27)
- [x] current hp (added in #19)
- [x] map star rating
